// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: users/usersrpc/users.proto

package usersgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserRpcService_GetUserByEmail_FullMethodName = "/usersgrpc.UserRpcService/GetUserByEmail"
)

// UserRpcServiceClient is the client API for UserRpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserRpcServiceClient interface {
	GetUserByEmail(ctx context.Context, in *GetUserByEmailInput, opts ...grpc.CallOption) (*GetUserByEmailResponse, error)
}

type userRpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserRpcServiceClient(cc grpc.ClientConnInterface) UserRpcServiceClient {
	return &userRpcServiceClient{cc}
}

func (c *userRpcServiceClient) GetUserByEmail(ctx context.Context, in *GetUserByEmailInput, opts ...grpc.CallOption) (*GetUserByEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserByEmailResponse)
	err := c.cc.Invoke(ctx, UserRpcService_GetUserByEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserRpcServiceServer is the server API for UserRpcService service.
// All implementations must embed UnimplementedUserRpcServiceServer
// for forward compatibility.
type UserRpcServiceServer interface {
	GetUserByEmail(context.Context, *GetUserByEmailInput) (*GetUserByEmailResponse, error)
	mustEmbedUnimplementedUserRpcServiceServer()
}

// UnimplementedUserRpcServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserRpcServiceServer struct{}

func (UnimplementedUserRpcServiceServer) GetUserByEmail(context.Context, *GetUserByEmailInput) (*GetUserByEmailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByEmail not implemented")
}
func (UnimplementedUserRpcServiceServer) mustEmbedUnimplementedUserRpcServiceServer() {}
func (UnimplementedUserRpcServiceServer) testEmbeddedByValue()                        {}

// UnsafeUserRpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserRpcServiceServer will
// result in compilation errors.
type UnsafeUserRpcServiceServer interface {
	mustEmbedUnimplementedUserRpcServiceServer()
}

func RegisterUserRpcServiceServer(s grpc.ServiceRegistrar, srv UserRpcServiceServer) {
	// If the following call pancis, it indicates UnimplementedUserRpcServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserRpcService_ServiceDesc, srv)
}

func _UserRpcService_GetUserByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByEmailInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserRpcServiceServer).GetUserByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserRpcService_GetUserByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserRpcServiceServer).GetUserByEmail(ctx, req.(*GetUserByEmailInput))
	}
	return interceptor(ctx, in, info, handler)
}

// UserRpcService_ServiceDesc is the grpc.ServiceDesc for UserRpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserRpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usersgrpc.UserRpcService",
	HandlerType: (*UserRpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserByEmail",
			Handler:    _UserRpcService_GetUserByEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users/usersrpc/users.proto",
}
